apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: v0.12.0-rc.1
  name: observatorium-xyz-thanos-rule
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/component: rule-evaluation-engine
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: thanos-rule
    app.kubernetes.io/part-of: observatorium
