apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api-gateway
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: HEAD-2020-04-16-v0.1.0
  name: observatorium-xyz-observatorium-api-gateway
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: observatorium-api-gateway
    app.kubernetes.io/part-of: observatorium
