apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: observatorium-xyz-api-gateway
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: v0.12.0-rc.1
  name: observatorium-xyz-observatorium-api-gateway-thanos-query
  namespace: observatorium
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: observatorium-xyz-api-gateway
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/part-of: observatorium
